/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Color Hunt palette (used for charts & badges)
        'palette-cream': '#F2EAE0',
        'palette-sky': '#B4D3D9',
        'palette-lavender': '#BDA6CE',
        'palette-purple': '#9B8EC7',
        'secondary-fixed-dim': '#B4D3D9',
        'on-error-container': '#93000a',
        'inverse-surface': '#2e3132',
        'on-secondary-fixed': '#191c1d',
        'primary-container': '#006b7e',
        'on-surface-variant': '#3f484b',
        'primary-fixed': '#adecff',
        'on-tertiary-container': '#ffd5b4',
        'tertiary-fixed-dim': '#ffb779',
        'tertiary-container': '#8b541e',
        'on-primary-container': '#9be9ff',
        'on-primary': '#ffffff',
        'secondary-container': '#B4D3D9',
        'inverse-primary': '#84d2e7',
        'on-error': '#ffffff',
        'on-background': '#191c1d',
        'surface-variant': '#e1e3e4',
        outline: '#6f797c',
        'on-primary-fixed-variant': '#004e5c',
        'surface-container-highest': '#e1e3e4',
        'on-primary-fixed': '#001f26',
        'surface-tint': '#00687a',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#ffdcc1',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#3f484b',
        'on-surface': '#191c1d',
        secondary: '#005160',
        'on-tertiary-fixed-variant': '#6b3a04',
        'surface-container-low': '#f3f4f5',
        'on-secondary': '#ffffff',
        tertiary: '#6e3d06',
        surface: '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        primary: '#005160',
        'surface-bright': '#f8f9fa',
        'outline-variant': '#bec8cc',
        background: '#f8f9fa',
        'primary-fixed-dim': '#84d2e7',
        'inverse-on-surface': '#f0f1f2',
        'surface-container-high': '#e7e8e9',
        'on-tertiary-fixed': '#2e1500',
        'surface-container': '#edeeef',
        'on-secondary-container': '#191c1d',
        'surface-dim': '#d9dadb',
        'secondary-fixed': '#B4D3D9',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.5rem',
        xl: '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
