/** @type {import('tailwindcss').Config} */
export default {
  content: ['./resources/views/**/*.blade.php', './resources/js/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'palette-sky': '#B4D3D9',
        'palette-lavender': '#BDA6CE',
        'palette-purple': '#9B8EC7',
        'secondary-fixed-dim': '#9aa8c4',
        'on-error-container': '#93000a',
        'inverse-surface': '#2a2438',
        'on-secondary-fixed': '#2a2438',
        'primary-container': '#d4c9e8',
        'on-surface-variant': '#5c5568',
        'primary-fixed': '#e8dff5',
        'on-tertiary-container': '#ffd5b4',
        'tertiary-fixed-dim': '#ffb779',
        'tertiary-container': '#8b541e',
        'on-primary-container': '#2a1a45',
        'on-primary': '#ffffff',
        'secondary-container': '#e8d8f0',
        'inverse-primary': '#c4b5dc',
        'on-error': '#ffffff',
        'on-background': '#2a2438',
        'surface-variant': '#d4e8eb',
        outline: '#7a9ea4',
        'on-primary-fixed-variant': '#4a3d6b',
        'surface-container-highest': '#e4e4e7',
        'on-primary-fixed': '#2a2438',
        'surface-tint': '#9B8EC7',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#ffdcc1',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#4a3f58',
        'on-surface': '#2a2438',
        secondary: '#BDA6CE',
        'on-tertiary-fixed-variant': '#6b3a04',
        'surface-container-low': '#ffffff',
        'on-secondary': '#2a2438',
        tertiary: '#6e3d06',
        surface: '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        primary: '#9B8EC7',
        'surface-bright': '#ffffff',
        'outline-variant': '#c4d9dc',
        background: '#ffffff',
        'primary-fixed-dim': '#BDA6CE',
        'inverse-on-surface': '#ffffff',
        'surface-container-high': '#f4f4f5',
        'on-tertiary-fixed': '#2e1500',
        'surface-container': '#fafafa',
        'on-secondary-container': '#2a2438',
        'surface-dim': '#f0f0f0',
        'secondary-fixed': '#B4D3D9',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.5rem',
        xl: '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
